#
# GNUmakefile - Generated by ProjectCenter
# Written by Philippe C.D. Robert <probert@siggraph.org>
#
# NOTE: Do NOT change this file -- ProjectCenter maintains it!
#
# Put all of your customisations in GNUmakefile.preamble and
# GNUmakefile.postamble
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Subprojects
#

#
# Main application
#

PACKAGE_NAME=StepBill
APP_NAME=StepBill
GNUSTEP_INSTALLATION_DIR=$(GNUSTEP_LOCAL_ROOT)/
StepBill_APPLICATION_ICON=icon.tiff
StepBill_MAIN_MODEL_FILE=StepBill.gorm

StepBill_LOCALIZED_RESOURCE_FILES= \
StepBill.gorm \
Localizable.strings \
story.txt \
rules.txt

StepBill_LANGUAGES= \
English \
Japanese \
Bulgarian

#
# Additional libraries
#

ADDITIONAL_GUI_LIBS += 

#
# Resource files
#

StepBill_RESOURCE_FILES= \
Defaults.plist \
tiffs/about.tiff \
tiffs/billD_3.tiff \
tiffs/maccpu.tiff \
tiffs/apple.tiff \
tiffs/billD_4.tiff \
tiffs/nextcpu.tiff \
tiffs/billA_0.tiff \
tiffs/billL_0.tiff \
tiffs/next.tiff \
tiffs/billA_10.tiff \
tiffs/billL_1.tiff \
tiffs/os2cpu.tiff \
tiffs/billA_11.tiff \
tiffs/billL_2.tiff \
tiffs/os2.tiff \
tiffs/billA_12.tiff \
tiffs/billR_0.tiff \
tiffs/palmcpu.tiff \
tiffs/billA_1.tiff \
tiffs/billR_1.tiff \
tiffs/palm.tiff \
tiffs/billA_2.tiff \
tiffs/billR_2.tiff \
tiffs/redhat.tiff \
tiffs/billA_3.tiff \
tiffs/bsdcpu.tiff \
tiffs/sgicpu.tiff \
tiffs/billA_4.tiff \
tiffs/bsd.tiff \
tiffs/sgi.tiff \
tiffs/billA_5.tiff \
tiffs/bucket.tiff \
tiffs/spark_0.tiff \
tiffs/billA_6.tiff \
tiffs/hand_down.tiff \
tiffs/spark_1.tiff \
tiffs/billA_7.tiff \
tiffs/hand_up.tiff \
tiffs/suncpu.tiff \
tiffs/billA_8.tiff \
tiffs/hurd.tiff \
tiffs/sun.tiff \
tiffs/billA_9.tiff \
tiffs/icon_orig.tiff \
tiffs/toaster.tiff \
tiffs/billD_0.tiff \
tiffs/icon.tiff \
tiffs/wingdows.tiff \
tiffs/billD_1.tiff \
tiffs/linux.tiff \
tiffs/billD_2.tiff \
tiffs/logo.tiff

#
# Header files
#

StepBill_HEADER_FILES= \
MBAqua.h \
MBBill.h \
MBBucket.h \
MBCable.h \
MBComputer.h \
MBGame.h \
MBHorde.h \
MBImageView.h \
MBNetwork.h \
MBOS.h \
MBScorelist.h \
MBSpark.h \
MBtypes.h \
MBUI.h \
MButil.h

#
# Class files
#

StepBill_OBJC_FILES= \
main.m \
MBAqua.m \
MBBill.m \
MBBucket.m \
MBCable.m \
MBComputer.m \
MBGame.m \
MBHorde.m \
MBImageView.m \
MBNetwork.m \
MBOS.m \
MBScorelist.m \
MBSpark.m \
MBUI.m

#
# C files
#

StepBill_C_FILES= 

ADDITIONAL_OBJCFLAGS = -Wno-import

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
